wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.23
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1756928455.0
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 51
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 50
      - 51
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.9.23
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val/minADE6
      5: 1
      6:
      - 1
    - 1: val/minFDE6
      5: 1
      6:
      - 1
    - 1: val/miss_rate
      5: 1
      6:
      - 1
    - 1: val/brier_fde
      5: 1
      6:
      - 1
    - 1: val/waymo/minADE6
      5: 1
      6:
      - 1
    - 1: val/waymo/minFDE6
      5: 1
      6:
      - 1
    - 1: val/waymo/miss_rate
      5: 1
      6:
      - 1
    - 1: val/waymo/brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/stationary_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/stationary_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/stationary_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/stationary_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_right_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_right_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_right_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_right_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_left_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_left_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_left_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/straight_left_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_turn_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_turn_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_turn_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_turn_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_turn_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_turn_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_turn_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_turn_brier_fde
      5: 1
      6:
      - 1
    - 1: val/kalman/easy_minADE6
      5: 1
      6:
      - 1
    - 1: val/kalman/easy_minFDE6
      5: 1
      6:
      - 1
    - 1: val/kalman/easy_miss_rate
      5: 1
      6:
      - 1
    - 1: val/kalman/easy_brier_fde
      5: 1
      6:
      - 1
    - 1: val/kalman/medium_minADE6
      5: 1
      6:
      - 1
    - 1: val/kalman/medium_minFDE6
      5: 1
      6:
      - 1
    - 1: val/kalman/medium_miss_rate
      5: 1
      6:
      - 1
    - 1: val/kalman/medium_brier_fde
      5: 1
      6:
      - 1
    - 1: val/kalman/hard_minADE6
      5: 1
      6:
      - 1
    - 1: val/kalman/hard_minFDE6
      5: 1
      6:
      - 1
    - 1: val/kalman/hard_miss_rate
      5: 1
      6:
      - 1
    - 1: val/kalman/hard_brier_fde
      5: 1
      6:
      - 1
    - 1: val/agent_types/vehicle_minADE6
      5: 1
      6:
      - 1
    - 1: val/agent_types/vehicle_minFDE6
      5: 1
      6:
      - 1
    - 1: val/agent_types/vehicle_miss_rate
      5: 1
      6:
      - 1
    - 1: val/agent_types/vehicle_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_u_turn_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_u_turn_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_u_turn_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/left_u_turn_brier_fde
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_u_turn_minADE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_u_turn_minFDE6
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_u_turn_miss_rate
      5: 1
      6:
      - 1
    - 1: val/traj_type/right_u_turn_brier_fde
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
